### ISSUE TITLE
Tibialyzer Problem

### ISSUE THREAD

**Issue by Ulquiorra44** [Mytherin/numpyllvm#1]
@Mytherin Could you help me ? i cannot open tibialyer with any of my programs :/
![fd](https://cloud.githubusercontent.com/assets/19747886/15799727/0fd2698c-2a66-11e6-88bc-ffa5a2c996f9.png)

**Comment by Mytherin** [comment]
You shouldn't open it with any program, you should open it as a program. Try to add the .exe suffix to the executable or right-click and press "Open" (not "Open with"). Also, please post issues with Tibialyzer on the Tibialyzer repository.
